
import { FaBirthdayCake, FaGift, } from "react-icons/fa";
import { GiBearFace, GiChocolateBar, GiFlowers, GiPartyPopper } from "react-icons/gi";
import { IoIosRestaurant } from "react-icons/io";
import { IoWoman } from "react-icons/io5";
import { MdFreeBreakfast, MdOutlineMan } from "react-icons/md";
import { TbMoodKid } from "react-icons/tb";
import * as FaIcons from "react-icons/fa";
import * as IoIcons from "react-icons/io";
import * as GiIcons from "react-icons/gi";
import * as MdIcons from "react-icons/md";



export interface Product {
  id: string;
  nombre: string;
  precio: number;
  imagenes: string[]; // Lista de URLs de imágenes
  descripcion: string;
  seccionIds: string[]; // IDs de las secciones asociadas
  descripcionCorta?: string;
  slug: string;
  tags: string[];
  createdAt?: Date;
  updatedAt?: Date;
  prioridad?: number;
  status?: "available" | "out_of_stock" | "discontinued";
}

export interface Section {
  id: string; // Identificador único de la sección
  name: string;
  iconName: string; // Nombre del ícono como cadena
  href: string; // Slug de la URL
  order: number; // Orden o prioridad
  isActive: boolean; // Estado activo/inactivo
}

export interface Articulo {
  id: string; // Identificador único
  slug: string; // Identificador para la ruta dinámica
  titulo: string; // Título del artículo
  descripcion: string; // Breve descripción del artículo
  imagen: string; // Imagen destacada para el carrusel
  imagenes: string[]; // Array de URLs para imágenes adicionales
  parrafos: string[]; // Contenido dividido en varios párrafos
  subtitulos: string[]; // Subtítulos para dividir secciones
  fechaPublicacion: Date; // Fecha de publicación
  autor: string; // Nombre del autor
  orden: number; // Orden del blog
}

// MenuSectionsBar
export const sectionsMenuSectionsBar: Section[] = [
  { name: "Cumpleaños", iconName: "FaBirthdayCake", href: "cumpleanos", isActive: true, order: 2, id: "1" },
  { name: "Desayunos", iconName: "IoIosRestaurant", href: "desayunos_sorpresa", isActive: true, order: 1, id: "2" },
  { name: "Detalles florales", iconName: "GiFlowers", href: "detalles_florales", isActive: true, order: 3, id: "3" },
  { name: "Peluches", iconName: "GiBearFace", href: "peluches", isActive: true, order: 4, id: "4" },
  { name: "Mugs", iconName: "MdFreeBreakfast", href: "mugs", isActive: true, order: 5, id: "5" },
  { name: "Chocolates", iconName: "GiChocolateBar", href: "chocolates", isActive: true, order: 6, id: "6" },
  { name: "Día del hombre", iconName: "MdOutlineMan", href: "dia_hombre", isActive: true, order: 7, id: "7" },
  { name: "Día de la mujer", iconName: "IoWoman", href: "dia_mujer", isActive: true, order: 8, id: "8" },
  { name: "Niños", iconName: "TbMoodKid", href: "ninos", isActive: true, order: 9, id: "9" },
  { name: "Cajas sorpresas", iconName: "FaGift", href: "cajas_sorpresa", isActive: true, order: 10, id: "10" },
  { name: "Decoraciones", iconName: "GiPartyPopper", href: "decoraciones", isActive: true, order: 11, id: "11" },
];

export interface SeedData {
  products: Product[];
  secciones: Section[]; // Acepta secciones sin `id`, arti
  articulos: Articulo[];
}



export const initialData: SeedData = {
  products: [
    {
      id: "prod-001",
      nombre: "Torta de Chocolate",
      precio: 25000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Deliciosa torta de chocolate con decoraciones temáticas de cumpleaños.",
      seccionIds: ["1"], // ID de la sección "Cumpleaños"
      descripcionCorta: "Torta temática para cumpleaños.",
      slug: "torta-de-chocolate",
      tags: ["torta", "chocolate", "cumpleaños"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 1,
      status: "available",
    },
    {
      id: "prod-002",
      nombre: "Globos Personalizados",
      precio: 50000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Paquete de globos personalizados para cumpleaños con mensajes únicos.",
      seccionIds: ["1"],
      descripcionCorta: "Globos temáticos personalizados.",
      slug: "globos-personalizados",
      tags: ["globos", "decoración", "cumpleaños"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 2,
      status: "available",
    },
    {
      id: "prod-003",
      nombre: "Caja de Dulces Sorpresa",
      precio: 75000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Caja con una selección de dulces y chocolates para celebrar en grande.",
      seccionIds: ["1"],
      descripcionCorta: "Caja de dulces temática.",
      slug: "caja-de-dulces",
      tags: ["dulces", "sorpresa", "cumpleaños"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 3,
      status: "available",
    },
    {
      id: "prod-004",
      nombre: "Ramo de Flores Temático",
      precio: 80000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Hermoso ramo de flores decorado especialmente para cumpleaños.",
      seccionIds: ["1"],
      descripcionCorta: "Flores para cumpleaños.",
      slug: "ramo-flores-cumple",
      tags: ["flores", "cumpleaños", "regalo"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 4,
      status: "available",
    },
    {
      id: "prod-005",
      nombre: "Set de Velas Temáticas",
      precio: 40000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Velas decorativas y aromáticas para ambientar cualquier fiesta de cumpleaños.",
      seccionIds: ["1"],
      descripcionCorta: "Velas decorativas de cumpleaños.",
      slug: "velas-de-cumpleaños",
      tags: ["velas", "cumpleaños", "decoración"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 5,
      status: "available",
    },
    {
      id: "prod-006",
      nombre: "Tarjeta de Felicitaciones",
      precio: 25000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Tarjeta personalizada con diseños únicos para cumpleaños.",
      seccionIds: ["1"],
      descripcionCorta: "Tarjeta temática de cumpleaños.",
      slug: "tarjeta-felicitaciones",
      tags: ["tarjeta", "regalo", "cumpleaños"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 6,
      status: "available",
    },
    {
      id: "prod-007",
      nombre: "Kit de Decoración de Fiesta",
      precio: 150000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Kit completo con decoraciones temáticas para fiestas de cumpleaños.",
      seccionIds: ["1"],
      descripcionCorta: "Kit para decorar fiestas.",
      slug: "kit-decoracion-cumpleaños",
      tags: ["decoración", "cumpleaños", "fiesta"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 7,
      status: "available",
    },
    {
      id: "prod-008",
      nombre: "Figura Decorativa de Pastel",
      precio: 60000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Figura decorativa temática para colocar en pasteles de cumpleaños.",
      seccionIds: ["1"],
      descripcionCorta: "Figura para pasteles.",
      slug: "figura-decorativa-pastel",
      tags: ["pastel", "decoración", "cumpleaños"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 8,
      status: "available",
    },
    {
      id: "prod-009",
      nombre: "Camiseta Personalizada",
      precio: 100000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Camiseta con diseños únicos y personalizados para festejar cumpleaños.",
      seccionIds: ["1"],
      descripcionCorta: "Camiseta temática de cumpleaños.",
      slug: "camiseta-personalizada",
      tags: ["ropa", "cumpleaños", "personalizado"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 9,
      status: "available",
    },
    {
      id: "prod-010",
      nombre: "Marco de Fotos Temático",
      precio: 90000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Marco decorativo para capturar recuerdos especiales de cumpleaños.",
      seccionIds: ["1"],
      descripcionCorta: "Marco de fotos temático.",
      slug: "marco-fotos-cumpleaños",
      tags: ["fotografía", "cumpleaños", "regalo"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 10,
      status: "available",
    },
    {
      id: "prod-011",
      nombre: "Desayuno Clásico",
      precio: 25000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Desayuno tradicional con huevos, pan y jugo natural.",
      seccionIds: ["2"], // ID de la sección "Desayunos"
      descripcionCorta: "Un desayuno tradicional.",
      slug: "desayuno-clasico",
      tags: ["desayuno", "tradicional", "jugo"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 1,
      status: "available",
    },
    {
      id: "prod-012",
      nombre: "Desayuno Americano",
      precio: 30000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Panqueques con miel, huevos revueltos y café.",
      seccionIds: ["2"],
      descripcionCorta: "Delicioso desayuno americano.",
      slug: "desayuno-americano",
      tags: ["panqueques", "café", "desayuno"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 2,
      status: "available",
    },
    {
      id: "prod-013",
      nombre: "Desayuno Saludable",
      precio: 28000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Yogur con granola, frutas frescas y un batido verde.",
      seccionIds: ["2"],
      descripcionCorta: "Opciones saludables para empezar el día.",
      slug: "desayuno-saludable",
      tags: ["yogur", "granola", "saludable"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 3,
      status: "available",
    },
    {
      id: "prod-014",
      nombre: "Desayuno Ejecutivo",
      precio: 35000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Tostadas francesas, huevos al gusto y café premium.",
      seccionIds: ["2"],
      descripcionCorta: "Elegancia en cada bocado.",
      slug: "desayuno-ejecutivo",
      tags: ["tostadas", "huevos", "café"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 4,
      status: "available",
    },
    {
      id: "prod-015",
      nombre: "Desayuno Colombiano",
      precio: 22000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Calentado con arepa, huevos pericos y chocolate caliente.",
      seccionIds: ["2"],
      descripcionCorta: "El sabor de casa.",
      slug: "desayuno-colombiano",
      tags: ["calentado", "arepa", "chocolate"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 5,
      status: "available",
    },
    {
      id: "prod-016",
      nombre: "Desayuno Infantil",
      precio: 20000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Cereal con leche, galletas y jugo de naranja.",
      seccionIds: ["2"],
      descripcionCorta: "Perfecto para los más pequeños.",
      slug: "desayuno-infantil",
      tags: ["cereal", "niños", "jugo"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 6,
      status: "available",
    },
    {
      id: "prod-017",
      nombre: "Desayuno Vegano",
      precio: 32000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Arepa de quinua, tofu revuelto y batido de frutos rojos.",
      seccionIds: ["2"],
      descripcionCorta: "Opciones veganas y deliciosas.",
      slug: "desayuno-vegano",
      tags: ["vegano", "arepa", "tofu"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 7,
      status: "available",
    },
    {
      id: "prod-018",
      nombre: "Desayuno Gourmet",
      precio: 40000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Croissant relleno, omelette de espinaca y café artesanal.",
      seccionIds: ["2"],
      descripcionCorta: "Sofisticación en cada plato.",
      slug: "desayuno-gourmet",
      tags: ["croissant", "omelette", "gourmet"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 8,
      status: "available",
    },
    {
      id: "prod-019",
      nombre: "Desayuno Energético",
      precio: 27000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Avena caliente con frutos secos y un jugo energético.",
      seccionIds: ["2"],
      descripcionCorta: "Energía para empezar el día.",
      slug: "desayuno-energetico",
      tags: ["avena", "frutos secos", "jugo"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 9,
      status: "available",
    },
    {
      id: "prod-020",
      nombre: "Desayuno Romántico",
      precio: 50000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Set especial con mimosas, fresas con crema y tostadas.",
      seccionIds: ["2"],
      descripcionCorta: "Perfecto para compartir.",
      slug: "desayuno-romantico",
      tags: ["romántico", "fresas", "mimosas"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 10,
      status: "available",
    },
    {
      id: "prod-021",
      nombre: "Ramo de Rosas",
      precio: 60000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Hermoso ramo de rosas frescas para cualquier ocasión especial.",
      seccionIds: ["3"], // ID de la sección "Detalles florales"
      descripcionCorta: "Rosas frescas y elegantes.",
      slug: "ramo-de-rosas",
      tags: ["flores", "rosas", "regalo"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 1,
      status: "available",
    },
    {
      id: "prod-022",
      nombre: "Arreglo Floral Mixto",
      precio: 75000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Arreglo con una combinación de flores tropicales y clásicas.",
      seccionIds: ["3"],
      descripcionCorta: "Arreglo floral con variedad de flores.",
      slug: "arreglo-floral-mixto",
      tags: ["flores", "arreglo", "tropical"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 2,
      status: "available",
    },
    {
      id: "prod-023",
      nombre: "Caja Floral Premium",
      precio: 120000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Caja de lujo con rosas y lirios decorados con detalles exclusivos.",
      seccionIds: ["3"],
      descripcionCorta: "Elegancia en una caja floral.",
      slug: "caja-floral-premium",
      tags: ["rosas", "lirios", "lujo"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 3,
      status: "available",
    },
    {
      id: "prod-024",
      nombre: "Florero de Tulipanes",
      precio: 90000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Tulipanes frescos en un elegante florero de cristal.",
      seccionIds: ["3"],
      descripcionCorta: "Tulipanes en un florero decorativo.",
      slug: "florero-de-tulipanes",
      tags: ["tulipanes", "decoración", "flores"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 4,
      status: "available",
    },
    {
      id: "prod-025",
      nombre: "Corazón de Rosas",
      precio: 150000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Arreglo en forma de corazón con rosas rojas para ocasiones románticas.",
      seccionIds: ["3"],
      descripcionCorta: "Un detalle perfecto para el amor.",
      slug: "corazon-de-rosas",
      tags: ["romántico", "rosas", "flores"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 5,
      status: "available",
    },
    {
      id: "prod-026",
      nombre: "Ramo de Margaritas",
      precio: 40000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Ramo simple pero encantador de margaritas frescas.",
      seccionIds: ["3"],
      descripcionCorta: "Margaritas frescas y naturales.",
      slug: "ramo-de-margaritas",
      tags: ["flores", "margaritas", "regalo"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 6,
      status: "available",
    },
    {
      id: "prod-027",
      nombre: "Cúpula de Rosas Encantadas",
      precio: 180000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Rosas preservadas en una cúpula de cristal para durar por años.",
      seccionIds: ["3"],
      descripcionCorta: "Rosas eternas en una cúpula.",
      slug: "cupula-de-rosas",
      tags: ["rosas", "preservadas", "lujo"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 7,
      status: "available",
    },
    {
      id: "prod-028",
      nombre: "Bouquet de Lirios",
      precio: 80000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Un bouquet elegante de lirios blancos y verdes decorativos.",
      seccionIds: ["3"],
      descripcionCorta: "Lirios frescos y elegantes.",
      slug: "bouquet-de-lirios",
      tags: ["lirios", "flores", "elegancia"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 8,
      status: "available",
    },
    {
      id: "prod-029",
      nombre: "Centro de Mesa Floral",
      precio: 100000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Decoración floral perfecta para eventos y celebraciones.",
      seccionIds: ["3"],
      descripcionCorta: "Centro de mesa decorativo.",
      slug: "centro-de-mesa-floral",
      tags: ["decoración", "eventos", "flores"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 9,
      status: "available",
    },
    {
      id: "prod-030",
      nombre: "Mini Bouquet Personalizado",
      precio: 35000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Pequeño bouquet con flores a elección, perfecto para un detalle especial.",
      seccionIds: ["3"],
      descripcionCorta: "Mini bouquet con flores personalizadas.",
      slug: "mini-bouquet-personalizado",
      tags: ["flores", "personalizado", "detalles"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 10,
      status: "available",
    },
    {
      id: "prod-031",
      nombre: "Oso de Peluche Clásico",
      precio: 45000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Oso de peluche suave y tierno, ideal para regalos.",
      seccionIds: ["4"], // ID de la sección "Peluches"
      descripcionCorta: "Peluche clásico y suave.",
      slug: "oso-de-peluche-clasico",
      tags: ["oso", "peluche", "regalo"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 1,
      status: "available",
    },
    {
      id: "prod-032",
      nombre: "Conejo de Peluche",
      precio: 50000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Conejo de peluche con orejas largas y detalles adorables.",
      seccionIds: ["4"],
      descripcionCorta: "Peluche de conejo adorable.",
      slug: "conejo-de-peluche",
      tags: ["conejo", "peluche", "suave"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 2,
      status: "available",
    },
    {
      id: "prod-033",
      nombre: "Peluche Gigante",
      precio: 120000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Un enorme peluche ideal para sorprender a alguien especial.",
      seccionIds: ["4"],
      descripcionCorta: "Peluche gigante y sorprendente.",
      slug: "peluche-gigante",
      tags: ["gigante", "peluche", "regalo"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 3,
      status: "available",
    },
    {
      id: "prod-034",
      nombre: "Peluche de Panda",
      precio: 60000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Adorable peluche de panda con textura suave y acabados de alta calidad.",
      seccionIds: ["4"],
      descripcionCorta: "Panda de peluche adorable.",
      slug: "peluche-de-panda",
      tags: ["panda", "peluche", "regalo"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 4,
      status: "available",
    },
    {
      id: "prod-035",
      nombre: "Peluche de Unicornio",
      precio: 75000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Un peluche mágico de unicornio con colores brillantes y suaves.",
      seccionIds: ["4"],
      descripcionCorta: "Unicornio mágico de peluche.",
      slug: "peluche-de-unicornio",
      tags: ["unicornio", "peluche", "fantasía"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 5,
      status: "available",
    },
    {
      id: "prod-036",
      nombre: "Peluche de Elefante",
      precio: 55000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Peluche de elefante con grandes orejas y textura suave.",
      seccionIds: ["4"],
      descripcionCorta: "Elefante de peluche adorable.",
      slug: "peluche-de-elefante",
      tags: ["elefante", "peluche", "tierno"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 6,
      status: "available",
    },
    {
      id: "prod-037",
      nombre: "Peluche de Gato",
      precio: 40000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Un lindo peluche de gato perfecto para amantes de los felinos.",
      seccionIds: ["4"],
      descripcionCorta: "Gato de peluche para regalar.",
      slug: "peluche-de-gato",
      tags: ["gato", "peluche", "suave"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 7,
      status: "available",
    },
    {
      id: "prod-038",
      nombre: "Peluche de Perrito",
      precio: 48000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Peluche de perrito con detalles realistas y suave al tacto.",
      seccionIds: ["4"],
      descripcionCorta: "Peluche de perrito adorable.",
      slug: "peluche-de-perrito",
      tags: ["perrito", "peluche", "adorable"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 8,
      status: "available",
    },
    {
      id: "prod-039",
      nombre: "Almohada de Peluche",
      precio: 70000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Almohada de peluche con diseño de animalito, perfecta para decorar y usar.",
      seccionIds: ["4"],
      descripcionCorta: "Almohada suave y adorable.",
      slug: "almohada-de-peluche",
      tags: ["almohada", "peluche", "decoración"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 9,
      status: "available",
    },
    {
      id: "prod-040",
      nombre: "Set de Mini Peluches",
      precio: 60000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Set de mini peluches con diferentes diseños adorables.",
      seccionIds: ["4"],
      descripcionCorta: "Mini peluches para coleccionar.",
      slug: "set-de-mini-peluches",
      tags: ["mini", "peluche", "colección"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 10,
      status: "available",
    },
    {
      id: "prod-041",
      nombre: "Mug Clásico Blanco",
      precio: 20000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Mug clásico blanco de cerámica, ideal para personalizar.",
      seccionIds: ["5"], // ID de la sección "Mugs"
      descripcionCorta: "Mug blanco clásico.",
      slug: "mug-clasico-blanco",
      tags: ["mug", "clásico", "personalizable"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 1,
      status: "available",
    },
    {
      id: "prod-042",
      nombre: "Mug con Mensaje Personalizado",
      precio: 30000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Mug personalizado con tu mensaje o diseño favorito.",
      seccionIds: ["5"],
      descripcionCorta: "Mug con diseño personalizado.",
      slug: "mug-mensaje-personalizado",
      tags: ["mug", "personalizado", "regalo"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 2,
      status: "available",
    },
    {
      id: "prod-043",
      nombre: "Mug de Corazón",
      precio: 25000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Mug de cerámica con asa en forma de corazón, perfecto para regalar.",
      seccionIds: ["5"],
      descripcionCorta: "Un detalle romántico.",
      slug: "mug-corazon",
      tags: ["mug", "romántico", "regalo"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 3,
      status: "available",
    },
    {
      id: "prod-044",
      nombre: "Mug Térmico",
      precio: 35000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Mug térmico de acero inoxidable, mantiene las bebidas calientes por más tiempo.",
      seccionIds: ["5"],
      descripcionCorta: "Mantén tu bebida caliente.",
      slug: "mug-termico",
      tags: ["mug", "térmico", "práctico"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 4,
      status: "available",
    },
    {
      id: "prod-045",
      nombre: "Mug Mágico",
      precio: 40000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Mug que revela un diseño cuando se llena con líquido caliente.",
      seccionIds: ["5"],
      descripcionCorta: "Un mug lleno de magia.",
      slug: "mug-magico",
      tags: ["mug", "mágico", "sorpresa"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 5,
      status: "available",
    },
    {
      id: "prod-046",
      nombre: "Mug Temático Navideño",
      precio: 30000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Mug con diseño temático navideño, ideal para la temporada.",
      seccionIds: ["5"],
      descripcionCorta: "Perfecto para Navidad.",
      slug: "mug-tematico-navideno",
      tags: ["mug", "navideño", "temático"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 6,
      status: "available",
    },
    {
      id: "prod-047",
      nombre: "Mug con Frases Inspiradoras",
      precio: 27000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Mug decorado con frases inspiradoras para empezar el día con energía.",
      seccionIds: ["5"],
      descripcionCorta: "Inspiración en cada sorbo.",
      slug: "mug-frases-inspiradoras",
      tags: ["mug", "frases", "inspiración"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 7,
      status: "available",
    },
    {
      id: "prod-048",
      nombre: "Mug para Parejas",
      precio: 50000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Set de mugs con diseños complementarios para parejas.",
      seccionIds: ["5"],
      descripcionCorta: "Un regalo perfecto para dos.",
      slug: "mug-para-parejas",
      tags: ["mug", "parejas", "romántico"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 8,
      status: "available",
    },
    {
      id: "prod-049",
      nombre: "Mug con Tapa y Cuchara",
      precio: 35000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Mug de cerámica con tapa de silicona y cuchara incluida.",
      seccionIds: ["5"],
      descripcionCorta: "Práctico y elegante.",
      slug: "mug-tapa-cuchara",
      tags: ["mug", "tapa", "cuchara"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 9,
      status: "available",
    },
    {
      id: "prod-050",
      nombre: "Mug de Viaje",
      precio: 45000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Mug portátil con diseño ergonómico para llevar tu bebida favorita a cualquier lugar.",
      seccionIds: ["5"],
      descripcionCorta: "Perfecto para viajeros.",
      slug: "mug-de-viaje",
      tags: ["mug", "viaje", "portátil"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 10,
      status: "available",
    },
    {
      id: "prod-051",
      nombre: "Caja de Bombones",
      precio: 40000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Caja con una selección de bombones rellenos de diferentes sabores.",
      seccionIds: ["6"], // ID de la sección "Chocolates"
      descripcionCorta: "Bombones rellenos exquisitos.",
      slug: "caja-de-bombones",
      tags: ["bombones", "chocolates", "regalo"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 1,
      status: "available",
    },
    {
      id: "prod-052",
      nombre: "Barra de Chocolate Artesanal",
      precio: 25000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Barra de chocolate artesanal 70% cacao con toques de frutos secos.",
      seccionIds: ["6"],
      descripcionCorta: "Chocolate artesanal de alta calidad.",
      slug: "barra-chocolate-artesanal",
      tags: ["chocolate", "artesanal", "cacao"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 2,
      status: "available",
    },
    {
      id: "prod-053",
      nombre: "Trufas de Chocolate",
      precio: 30000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Deliciosas trufas de chocolate con relleno suave y cremoso.",
      seccionIds: ["6"],
      descripcionCorta: "Trufas con relleno cremoso.",
      slug: "trufas-de-chocolate",
      tags: ["trufas", "chocolate", "exquisito"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 3,
      status: "available",
    },
    {
      id: "prod-054",
      nombre: "Fondue de Chocolate",
      precio: 60000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Set de fondue con chocolate oscuro y blanco para acompañar con frutas.",
      seccionIds: ["6"],
      descripcionCorta: "Set para disfrutar el fondue.",
      slug: "fondue-de-chocolate",
      tags: ["fondue", "chocolate", "frutas"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 4,
      status: "available",
    },
    {
      id: "prod-055",
      nombre: "Chocolates con Licor",
      precio: 50000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Bombones de chocolate rellenos con licores selectos como ron y whisky.",
      seccionIds: ["6"],
      descripcionCorta: "Bombones rellenos con licor.",
      slug: "chocolates-con-licor",
      tags: ["chocolate", "licor", "bombones"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 5,
      status: "available",
    },
    {
      id: "prod-056",
      nombre: "Caja de Chocolates Personalizados",
      precio: 70000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Chocolates personalizados con nombres o mensajes especiales.",
      seccionIds: ["6"],
      descripcionCorta: "Chocolates con mensajes personalizados.",
      slug: "caja-chocolates-personalizados",
      tags: ["chocolates", "personalizado", "regalo"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 6,
      status: "available",
    },
    {
      id: "prod-057",
      nombre: "Chocolates en Forma de Corazón",
      precio: 35000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Chocolates en forma de corazón, ideales para ocasiones románticas.",
      seccionIds: ["6"],
      descripcionCorta: "Romántico y delicioso.",
      slug: "chocolates-corazon",
      tags: ["chocolates", "corazón", "romántico"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 7,
      status: "available",
    },
    {
      id: "prod-058",
      nombre: "Caja de Mini Chocolates",
      precio: 20000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Mini chocolates surtidos en una caja decorativa.",
      seccionIds: ["6"],
      descripcionCorta: "Mini chocolates surtidos.",
      slug: "caja-mini-chocolates",
      tags: ["mini", "chocolates", "regalo"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 8,
      status: "available",
    },
    {
      id: "prod-059",
      nombre: "Bombones de Chocolate Blanco",
      precio: 30000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Bombones de chocolate blanco rellenos con crema de vainilla.",
      seccionIds: ["6"],
      descripcionCorta: "Chocolate blanco y cremoso.",
      slug: "bombones-chocolate-blanco",
      tags: ["bombones", "chocolate blanco", "cremoso"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 9,
      status: "available",
    },
    {
      id: "prod-060",
      nombre: "Set de Chocolates Gourmet",
      precio: 80000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Selección exclusiva de chocolates gourmet con sabores únicos.",
      seccionIds: ["6"],
      descripcionCorta: "Chocolates exclusivos y elegantes.",
      slug: "set-chocolates-gourmet",
      tags: ["gourmet", "chocolates", "exclusivo"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 10,
      status: "available",

    }, {
      id: "prod-061",
      nombre: "Set de Afeitado Premium",
      precio: 80000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Set de afeitado con espuma, brocha y navaja de alta calidad.",
      seccionIds: ["7"], // ID de la sección "Día del Hombre"
      descripcionCorta: "Un regalo práctico y elegante.",
      slug: "set-afeitado-premium",
      tags: ["afeitado", "premium", "regalo"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 1,
      status: "available",
    },
    {
      id: "prod-062",
      nombre: "Kit de Barbacoa",
      precio: 120000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Kit con utensilios esenciales para disfrutar de un buen asado.",
      seccionIds: ["7"],
      descripcionCorta: "Perfecto para amantes de la parrilla.",
      slug: "kit-de-barbacoa",
      tags: ["barbacoa", "utensilios", "hombre"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 2,
      status: "available",
    },
    {
      id: "prod-063",
      nombre: "Set de Herramientas Multiusos",
      precio: 100000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Set compacto de herramientas multiusos, ideal para cualquier ocasión.",
      seccionIds: ["7"],
      descripcionCorta: "Práctico y funcional.",
      slug: "set-herramientas-multiusos",
      tags: ["herramientas", "multiusos", "regalo"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 3,
      status: "available",
    },
    {
      id: "prod-064",
      nombre: "Reloj Deportivo",
      precio: 150000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Reloj resistente al agua con cronómetro y diseño moderno.",
      seccionIds: ["7"],
      descripcionCorta: "Perfecto para hombres activos.",
      slug: "reloj-deportivo",
      tags: ["reloj", "deportivo", "regalo"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 4,
      status: "available",
    },
    {
      id: "prod-065",
      nombre: "Caja de Cervezas Artesanales",
      precio: 70000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Selección de cervezas artesanales de diferentes estilos.",
      seccionIds: ["7"],
      descripcionCorta: "Un regalo para disfrutar.",
      slug: "caja-cervezas-artesanales",
      tags: ["cervezas", "artesanales", "regalo"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 5,
      status: "available",
    },
    {
      id: "prod-066",
      nombre: "Gorra Personalizada",
      precio: 40000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Gorra ajustable con diseños personalizados al gusto.",
      seccionIds: ["7"],
      descripcionCorta: "Comodidad y estilo.",
      slug: "gorra-personalizada",
      tags: ["gorra", "personalizada", "hombre"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 6,
      status: "available",
    },
    {
      id: "prod-067",
      nombre: "Pulsera de Cuero",
      precio: 50000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Pulsera de cuero con detalles metálicos, ideal para un look casual.",
      seccionIds: ["7"],
      descripcionCorta: "Un accesorio elegante.",
      slug: "pulsera-de-cuero",
      tags: ["pulsera", "cuero", "hombre"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 7,
      status: "available",
    },
    {
      id: "prod-068",
      nombre: "Perfume Masculino",
      precio: 120000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Fragancia fresca y moderna, perfecta para cualquier ocasión.",
      seccionIds: ["7"],
      descripcionCorta: "Elegancia en un perfume.",
      slug: "perfume-masculino",
      tags: ["perfume", "masculino", "regalo"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 8,
      status: "available",
    },
    {
      id: "prod-069",
      nombre: "Bolso Deportivo",
      precio: 90000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Bolso práctico y resistente, ideal para el gimnasio o viajes cortos.",
      seccionIds: ["7"],
      descripcionCorta: "Práctico y moderno.",
      slug: "bolso-deportivo",
      tags: ["bolso", "deportivo", "hombre"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 9,
      status: "available",
    },
    {
      id: "prod-070",
      nombre: "Set de Whisky y Accesorios",
      precio: 180000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Set con una botella de whisky premium y accesorios como vasos y piedras enfriadoras.",
      seccionIds: ["7"],
      descripcionCorta: "Un regalo sofisticado.",
      slug: "set-whisky-accesorios",
      tags: ["whisky", "accesorios", "regalo"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 10,
      status: "available",
    }, {
      id: "prod-071",
      nombre: "Ramo de Rosas Rojas",
      precio: 70000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Hermoso ramo de rosas rojas, símbolo de amor y aprecio.",
      seccionIds: ["8"], // ID de la sección "Día de la Mujer"
      descripcionCorta: "Rosas rojas para celebrar.",
      slug: "ramo-de-rosas-rojas",
      tags: ["rosas", "flores", "mujer"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 1,
      status: "available",
    },
    {
      id: "prod-072",
      nombre: "Set de Belleza Natural",
      precio: 120000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Set de productos de belleza natural, ideal para cuidar la piel.",
      seccionIds: ["8"],
      descripcionCorta: "Belleza y cuidado.",
      slug: "set-belleza-natural",
      tags: ["belleza", "cuidado", "mujer"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 2,
      status: "available",
    },
    {
      id: "prod-073",
      nombre: "Collar de Plata con Dije",
      precio: 90000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Collar de plata con un dije en forma de corazón, elegante y delicado.",
      seccionIds: ["8"],
      descripcionCorta: "Un accesorio elegante.",
      slug: "collar-plata-dije",
      tags: ["collar", "plata", "regalo"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 3,
      status: "available",
    },
    {
      id: "prod-074",
      nombre: "Caja de Chocolates Especial",
      precio: 60000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Caja con una selección de chocolates premium para compartir.",
      seccionIds: ["8"],
      descripcionCorta: "Dulzura en cada bocado.",
      slug: "caja-chocolates-especial",
      tags: ["chocolates", "mujer", "regalo"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 4,
      status: "available",
    },
    {
      id: "prod-075",
      nombre: "Bouquet de Tulipanes",
      precio: 85000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Tulipanes frescos en una presentación delicada y colorida.",
      seccionIds: ["8"],
      descripcionCorta: "Un regalo lleno de vida.",
      slug: "bouquet-tulipanes",
      tags: ["flores", "tulipanes", "mujer"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 5,
      status: "available",
    },
    {
      id: "prod-076",
      nombre: "Perfume Floral",
      precio: 150000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Fragancia floral ligera y fresca, perfecta para el día a día.",
      seccionIds: ["8"],
      descripcionCorta: "Elegancia en una fragancia.",
      slug: "perfume-floral",
      tags: ["perfume", "floral", "mujer"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 6,
      status: "available",
    },
    {
      id: "prod-077",
      nombre: "Kit de Spa en Casa",
      precio: 130000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Kit completo para un momento de relajación en casa, incluye velas y sales de baño.",
      seccionIds: ["8"],
      descripcionCorta: "Relajación en casa.",
      slug: "kit-spa-en-casa",
      tags: ["spa", "relajación", "mujer"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 7,
      status: "available",
    },
    {
      id: "prod-078",
      nombre: "Set de Tazas Personalizadas",
      precio: 50000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Set de dos tazas personalizadas con mensajes especiales para ella.",
      seccionIds: ["8"],
      descripcionCorta: "Un detalle único.",
      slug: "set-tazas-personalizadas",
      tags: ["tazas", "personalizado", "regalo"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 8,
      status: "available",
    },
    {
      id: "prod-079",
      nombre: "Agenda y Pluma Elegante",
      precio: 70000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Agenda con diseño floral y una pluma elegante en set.",
      seccionIds: ["8"],
      descripcionCorta: "Organización con estilo.",
      slug: "agenda-pluma-elegante",
      tags: ["agenda", "elegante", "mujer"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 9,
      status: "available",
    },
    {
      id: "prod-080",
      nombre: "Caja de Regalo Personalizada",
      precio: 100000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Caja con productos personalizados, ideal para un regalo único.",
      seccionIds: ["8"],
      descripcionCorta: "Un regalo especial.",
      slug: "caja-regalo-personalizada",
      tags: ["caja", "personalizado", "mujer"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 10,
      status: "available",
    }, {
      id: "prod-081",
      nombre: "Set de Colores y Cuaderno",
      precio: 25000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Set de colores brillantes y un cuaderno de dibujos temático.",
      seccionIds: ["9"], // ID de la sección "Niños"
      descripcionCorta: "Para los pequeños artistas.",
      slug: "set-colores-cuaderno",
      tags: ["colores", "niños", "arte"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 1,
      status: "available",
    },
    {
      id: "prod-082",
      nombre: "Muñeco de Peluche",
      precio: 40000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Peluche suave y divertido en forma de personajes animados.",
      seccionIds: ["9"],
      descripcionCorta: "Un compañero adorable.",
      slug: "muneco-peluche",
      tags: ["peluche", "niños", "juguete"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 2,
      status: "available",
    },
    {
      id: "prod-083",
      nombre: "Rompecabezas Infantil",
      precio: 30000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Rompecabezas colorido de 50 piezas, ideal para desarrollar habilidades cognitivas.",
      seccionIds: ["9"],
      descripcionCorta: "Diversión y aprendizaje.",
      slug: "rompecabezas-infantil",
      tags: ["rompecabezas", "juguete", "niños"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 3,
      status: "available",
    },
    {
      id: "prod-084",
      nombre: "Kit de Manualidades",
      precio: 50000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Kit con materiales para crear arte y manualidades divertidas.",
      seccionIds: ["9"],
      descripcionCorta: "Creatividad sin límites.",
      slug: "kit-de-manualidades",
      tags: ["manualidades", "arte", "niños"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 4,
      status: "available",
    },
    {
      id: "prod-085",
      nombre: "Cuento Infantil Ilustrado",
      precio: 35000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Cuento infantil con ilustraciones coloridas y una historia emocionante.",
      seccionIds: ["9"],
      descripcionCorta: "Un mundo de aventuras.",
      slug: "cuento-infantil-ilustrado",
      tags: ["cuento", "niños", "lectura"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 5,
      status: "available",
    },
    {
      id: "prod-086",
      nombre: "Juguete Didáctico",
      precio: 60000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Juguete interactivo para desarrollar habilidades matemáticas y motoras.",
      seccionIds: ["9"],
      descripcionCorta: "Aprender jugando.",
      slug: "juguete-didactico",
      tags: ["juguete", "educativo", "niños"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 6,
      status: "available",
    },
    {
      id: "prod-087",
      nombre: "Caja de Pintura Lavable",
      precio: 45000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Caja con pintura lavable y pinceles para pequeños artistas.",
      seccionIds: ["9"],
      descripcionCorta: "Pintura segura y divertida.",
      slug: "caja-pintura-lavable",
      tags: ["pintura", "arte", "niños"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 7,
      status: "available",
    },
    {
      id: "prod-088",
      nombre: "Carrito de Juguete",
      precio: 30000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Carrito resistente con diseños divertidos para los pequeños.",
      seccionIds: ["9"],
      descripcionCorta: "Diversión sobre ruedas.",
      slug: "carrito-juguete",
      tags: ["carrito", "juguete", "niños"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 8,
      status: "available",
    },
    {
      id: "prod-089",
      nombre: "Set de Dinosaurios",
      precio: 40000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Figuras de dinosaurios para aprender y jugar.",
      seccionIds: ["9"],
      descripcionCorta: "Un regalo prehistórico.",
      slug: "set-dinosaurios",
      tags: ["dinosaurios", "juguete", "niños"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 9,
      status: "available",
    },
    {
      id: "prod-090",
      nombre: "Set de Globos Temáticos",
      precio: 20000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Globos decorativos con personajes favoritos para fiestas infantiles.",
      seccionIds: ["9"],
      descripcionCorta: "Perfecto para fiestas.",
      slug: "set-globos-tematicos",
      tags: ["globos", "fiestas", "niños"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 10,
      status: "available",
    }, {
      id: "prod-091",
      nombre: "Caja Sorpresa de Dulces",
      precio: 60000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Caja llena de dulces y chocolates surtidos para disfrutar.",
      seccionIds: ["10"], // ID de la sección "Cajas Sorpresas"
      descripcionCorta: "Dulzura en una caja.",
      slug: "caja-sorpresa-dulces",
      tags: ["caja", "dulces", "sorpresa"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 1,
      status: "available",
    },
    {
      id: "prod-092",
      nombre: "Caja Sorpresa de Spa",
      precio: 120000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Incluye velas, sales de baño y productos para un día de spa en casa.",
      seccionIds: ["10"],
      descripcionCorta: "Relax y cuidado personal.",
      slug: "caja-sorpresa-spa",
      tags: ["caja", "spa", "sorpresa"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 2,
      status: "available",
    },
    {
      id: "prod-093",
      nombre: "Caja Sorpresa de Chocolates",
      precio: 90000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Selección de chocolates premium y bombones en una elegante caja.",
      seccionIds: ["10"],
      descripcionCorta: "Para los amantes del chocolate.",
      slug: "caja-sorpresa-chocolates",
      tags: ["caja", "chocolates", "sorpresa"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 3,
      status: "available",
    },
    {
      id: "prod-094",
      nombre: "Caja de Regalo Personalizada",
      precio: 150000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Caja sorpresa con productos seleccionados según las preferencias del destinatario.",
      seccionIds: ["10"],
      descripcionCorta: "Un regalo único y especial.",
      slug: "caja-regalo-personalizada",
      tags: ["caja", "personalizado", "regalo"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 4,
      status: "available",
    },
    {
      id: "prod-095",
      nombre: "Caja Sorpresa de Amor",
      precio: 100000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Incluye detalles románticos como peluches, chocolates y una carta personalizada.",
      seccionIds: ["10"],
      descripcionCorta: "Perfecta para un gesto romántico.",
      slug: "caja-sorpresa-amor",
      tags: ["caja", "romántico", "sorpresa"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 5,
      status: "available",
    },
    {
      id: "prod-096",
      nombre: "Caja Sorpresa Gourmet",
      precio: 180000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Incluye vinos, quesos y snacks gourmet en una presentación elegante.",
      seccionIds: ["10"],
      descripcionCorta: "Un regalo exclusivo.",
      slug: "caja-sorpresa-gourmet",
      tags: ["caja", "gourmet", "regalo"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 6,
      status: "available",
    },
    {
      id: "prod-097",
      nombre: "Caja Sorpresa para Niños",
      precio: 70000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Llena de juguetes pequeños, dulces y actividades divertidas.",
      seccionIds: ["10"],
      descripcionCorta: "Diversión asegurada para los niños.",
      slug: "caja-sorpresa-ninos",
      tags: ["caja", "niños", "sorpresa"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 7,
      status: "available",
    },
    {
      id: "prod-098",
      nombre: "Caja Sorpresa de Desayuno",
      precio: 90000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Incluye jugos, panecillos y frutas frescas en una caja decorativa.",
      seccionIds: ["10"],
      descripcionCorta: "Un desayuno especial en una caja.",
      slug: "caja-sorpresa-desayuno",
      tags: ["caja", "desayuno", "sorpresa"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 8,
      status: "available",
    },
    {
      id: "prod-099",
      nombre: "Caja Sorpresa de Peluches",
      precio: 80000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Incluye una colección de mini peluches adorables y coloridos.",
      seccionIds: ["10"],
      descripcionCorta: "Un regalo adorable.",
      slug: "caja-sorpresa-peluches",
      tags: ["caja", "peluches", "sorpresa"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 9,
      status: "available",
    },
    {
      id: "prod-100",
      nombre: "Caja Sorpresa de Cumpleaños",
      precio: 110000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Incluye globos, decoraciones y un pastel pequeño.",
      seccionIds: ["10"],
      descripcionCorta: "Todo lo necesario para una celebración.",
      slug: "caja-sorpresa-cumpleanos",
      tags: ["caja", "cumpleaños", "sorpresa"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 10,
      status: "available",
    }, {
      id: "prod-101",
      nombre: "Guirnaldas de Papel",
      precio: 20000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Coloridas guirnaldas de papel para decorar cualquier ocasión especial.",
      seccionIds: ["11"], // ID de la sección "Decoraciones"
      descripcionCorta: "Guirnaldas festivas y vibrantes.",
      slug: "guirnaldas-de-papel",
      tags: ["guirnaldas", "decoración", "fiesta"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 1,
      status: "available",
    },
    {
      id: "prod-102",
      nombre: "Luces LED Decorativas",
      precio: 40000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Luces LED con varios modos de iluminación, ideales para ambientes cálidos.",
      seccionIds: ["11"],
      descripcionCorta: "Ilumina tus eventos con estilo.",
      slug: "luces-led-decorativas",
      tags: ["luces", "LED", "decoración"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 2,
      status: "available",
    },
    {
      id: "prod-103",
      nombre: "Arco de Globos",
      precio: 80000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Set completo para crear un impresionante arco de globos.",
      seccionIds: ["11"],
      descripcionCorta: "Una entrada espectacular.",
      slug: "arco-de-globos",
      tags: ["globos", "arco", "decoración"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 3,
      status: "available",
    },
    {
      id: "prod-104",
      nombre: "Centros de Mesa Personalizados",
      precio: 60000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Centros de mesa personalizados con temática especial para eventos.",
      seccionIds: ["11"],
      descripcionCorta: "Elegancia en cada mesa.",
      slug: "centros-de-mesa",
      tags: ["decoración", "centro de mesa", "personalizado"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 4,
      status: "available",
    },
    {
      id: "prod-105",
      nombre: "Carteles de Bienvenida",
      precio: 30000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Carteles personalizados para dar una cálida bienvenida a tus invitados.",
      seccionIds: ["11"],
      descripcionCorta: "Un toque personal para tus eventos.",
      slug: "carteles-de-bienvenida",
      tags: ["carteles", "personalizado", "decoración"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 5,
      status: "available",
    },
    {
      id: "prod-106",
      nombre: "Velas Aromáticas Decorativas",
      precio: 50000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Velas aromáticas en diseños decorativos para ambientar espacios.",
      seccionIds: ["11"],
      descripcionCorta: "Ambiente cálido y fragante.",
      slug: "velas-aromaticas",
      tags: ["velas", "aromáticas", "decoración"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 6,
      status: "available",
    },
    {
      id: "prod-107",
      nombre: "Globos Personalizados",
      precio: 20000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Globos con mensajes personalizados para cumpleaños o eventos especiales.",
      seccionIds: ["11"],
      descripcionCorta: "Detalles únicos para tus fiestas.",
      slug: "globos-personalizados",
      tags: ["globos", "personalizado", "fiestas"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 7,
      status: "available",
    },
    {
      id: "prod-108",
      nombre: "Paneles Decorativos de Fondo",
      precio: 100000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Paneles decorativos con diseño personalizado para fotos o eventos.",
      seccionIds: ["11"],
      descripcionCorta: "Un fondo perfecto para tus fotos.",
      slug: "paneles-decorativos",
      tags: ["paneles", "fondo", "decoración"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 8,
      status: "available",
    },
    {
      id: "prod-109",
      nombre: "Manteles Temáticos",
      precio: 25000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Manteles con diseños temáticos para cumpleaños o reuniones especiales.",
      seccionIds: ["11"],
      descripcionCorta: "Un toque único en tu mesa.",
      slug: "manteles-tematicos",
      tags: ["manteles", "temático", "decoración"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 9,
      status: "available",
    },
    {
      id: "prod-110",
      nombre: "Portavelas Decorativos",
      precio: 45000,
      imagenes: ["/imgs/imagen-prueba.webp", "/imgs/imagen-prueba2.webp"],
      descripcion: "Elegantes portavelas para decorar mesas y espacios interiores.",
      seccionIds: ["11"],
      descripcionCorta: "Un detalle elegante para cualquier ocasión.",
      slug: "portavelas-decorativos",
      tags: ["portavelas", "elegante", "decoración"],
      createdAt: new Date(),
      updatedAt: new Date(),
      prioridad: 10,
      status: "available",
    },
  ],
  secciones: sectionsMenuSectionsBar,
  articulos: [
    {
      id: "1",
      orden: 1,
      titulo: "10 Ideas de Regalos para Amor y Amistad",
      imagen: "/imgs/blog1.webp",
      descripcion: "Sorprende a tus seres queridos con estas ideas únicas para amor y amistad.",
      slug: "ideas-regalos-amor-amistad",
      imagenes: ["/imgs/blog1.webp", "/imgs/blog2.webp",],
      parrafos: [
        "Amor y Amistad es la ocasión perfecta para demostrar cuánto valoras a las personas especiales en tu vida. Pero encontrar el regalo ideal puede ser todo un desafío. En este artículo, te presentamos 10 ideas de regalos únicos que te ayudarán a expresar tus sentimientos de una manera inolvidable.",
        "¿Por qué no empezar con un detalle personalizado? Un regalo con un toque único, como una taza con una foto especial o una joya grabada, muestra que realmente pensaste en esa persona. Los regalos personalizados son una excelente manera de destacar en esta fecha tan especial.",
        "Las experiencias son otro regalo que nunca pasa de moda. Una cena romántica, una visita a un lugar especial o incluso una sesión de spa para dos pueden crear recuerdos inolvidables. A veces, lo mejor que puedes regalar no es un objeto, sino un momento compartido.",
        "Si buscas algo más tradicional, las flores y los chocolates siempre son una apuesta segura. Considera una combinación de ambos, o elige opciones más sofisticadas como ramos de flores preservadas o chocolates gourmet.",
        "Finalmente, para quienes buscan un regalo práctico, una suscripción a un servicio que esa persona use frecuentemente, como un streaming de música o una caja de productos mensuales, puede ser el detalle perfecto. Estas opciones demuestran atención y cuidado hacia los gustos personales del destinatario."
      ],
      subtitulos: [
        "Regalos Personalizados: Un Toque Único",
        "Regala Experiencias Inolvidables",
        "Flores y Chocolates: La Tradición que Nunca Falla",
        "Suscripciones y Detalles Prácticos"
      ],
      fechaPublicacion: new Date("2024-02-14"),
      autor: "Equipo Creativo de Regalos Únicos",
    },
    {
      id: "2",
      orden: 2,
      titulo: "Cómo Elegir el Regalo Perfecto para un Cumpleaños",
      imagen: "/imgs/blog2.webp",
      descripcion: "Descubre cómo encontrar el regalo ideal para sorprender en cualquier cumpleaños.",
      slug: "regalo-perfecto-cumpleanos",
      imagenes: ["/imgs/blog2.webp", "/imgs/blog1.webp", "/imgs/blog3.webp"],
      parrafos: [
        "Elegir el regalo perfecto para un cumpleaños puede ser todo un desafío, pero también una oportunidad para mostrar cuánto te importa esa persona especial. En este artículo, exploraremos estrategias y consejos para asegurarte de que tu elección sea memorable y significativa.",
        "El primer paso es pensar en los intereses y pasatiempos de la persona que recibirá el regalo. ¿Le gusta leer? ¿Es amante de los deportes? ¿Disfruta la tecnología? Un regalo que refleje sus gustos demuestra atención y cuidado.",
        "La personalización siempre es una gran idea. Un regalo único, como una camiseta con un diseño especial o una agenda grabada con su nombre, puede convertir algo simple en algo verdaderamente especial.",
        "Otra opción es optar por experiencias en lugar de objetos materiales. Un boleto para un concierto, una cena en su restaurante favorito o incluso una escapada de fin de semana son regalos que dejan recuerdos imborrables.",
        "Por último, no olvides la importancia de la presentación. Un empaque bonito y un mensaje sincero pueden transformar incluso el regalo más sencillo en algo significativo."
      ],
      subtitulos: [
        "Conoce los Gustos e Intereses del Festejado",
        "La Magia de los Regalos Personalizados",
        "Regala Experiencias: Crea Momentos Inolvidables",
        "La Presentación También Importa"
      ],
      fechaPublicacion: new Date("2024-03-10"),
      autor: "Equipo Creativo de Regalos Únicos",
    },
    {
      id: "3",
      orden: 3,
      titulo: "Fechas Especiales en Colombia 2024",
      imagen: "/imgs/blog3.webp",
      descripcion: "Consulta las fechas más importantes del año y encuentra el regalo ideal para cada ocasión.",
      slug: "fechas-especiales-2024",
      imagenes: ["/imgs/blog3.webp", "/imgs/blog1.webp", "/imgs/blog2.webp"],
      parrafos: [
        "Colombia está llena de tradiciones y fechas especiales que celebran la cultura, el amor y la amistad. Estas ocasiones no solo son una oportunidad para compartir con seres queridos, sino también para expresar tus sentimientos a través de regalos significativos.",
        "El Día de la Mujer, celebrado el 8 de marzo, es una de las fechas más importantes. Es el momento perfecto para honrar a las mujeres especiales en tu vida con flores, chocolates o detalles personalizados que reflejen su valor único.",
        "En septiembre, llega el Día del Amor y la Amistad, donde los colombianos intercambian regalos para demostrar aprecio por sus parejas y amigos. Ideas como cartas escritas a mano, cenas románticas o pequeños detalles sorpresa son ideales para esta ocasión.",
        "No podemos olvidar las fiestas decembrinas, especialmente la Navidad y el Día de las Velitas, que llenan los hogares de alegría y unión. Regalos como decoraciones navideñas personalizadas, juguetes para los más pequeños o experiencias familiares hacen de estas fechas momentos inolvidables.",
        "Por último, los aniversarios personales, como cumpleaños o celebraciones de bodas, también tienen un lugar especial. Aprovecha estas ocasiones para regalar algo significativo y demostrar tu cariño de una manera única."
      ],
      subtitulos: [
        "Día de la Mujer: 8 de Marzo",
        "Amor y Amistad: Celebración en Septiembre",
        "Fiestas Decembrinas: Navidad y Día de las Velitas",
        "Aniversarios Personales: Momentos Únicos"
      ],
      fechaPublicacion: new Date("2024-01-01"),
      autor: "Equipo Creativo de Regalos Únicos",
    },
    {
      id: "4",
      orden: 4,
      titulo: "Regalos Ecológicos y Sostenibles: Sorprende con Consciencia",
      imagen: "/imgs/blog-ecologicos.webp",
      descripcion: "Descubre ideas de regalos sostenibles que cuidan el planeta y demuestran tu amor por los demás.",
      slug: "regalos-ecologicos-sostenibles",
      imagenes: ["/imgs/blog-ecologicos2.webp", "/imgs/blog-eco1.webp", "/imgs/blog-eco2.webp"],
      parrafos: [
        "En un mundo donde cada vez somos más conscientes del impacto ambiental, los regalos ecológicos y sostenibles son una excelente manera de mostrar amor y cuidado tanto por las personas como por el planeta. En este artículo, exploramos ideas de regalos que combinan estilo, utilidad y responsabilidad ecológica.",
        "Un gran punto de partida son los productos reutilizables. Botellas de agua de acero inoxidable, bolsas de tela para compras o incluso kits de cubiertos reutilizables son opciones prácticas y amigables con el medio ambiente.",
        "Otro tipo de regalo sostenible son los productos hechos a mano o de materiales reciclados. Desde joyería artesanal hasta muebles restaurados, estos regalos tienen un toque único y ayudan a reducir el consumo de nuevos recursos.",
        "Las experiencias también son regalos sostenibles. Un taller de cocina vegana, una sesión de yoga al aire libre o una suscripción a servicios de streaming eliminan el consumo físico mientras crean recuerdos duraderos.",
        "Finalmente, considera apoyar marcas que promuevan prácticas responsables. Busca etiquetas de comercio justo, empaques biodegradables y productos con certificaciones ecológicas. Regalar con consciencia nunca fue tan accesible."
      ],
      subtitulos: [
        "Productos Reutilizables: Prácticos y Responsables",
        "Creatividad con Materiales Reciclados",
        "Regala Experiencias, no Objetos",
        "Elige Marcas con Impacto Positivo"
      ],
      fechaPublicacion: new Date("2024-04-22"),
      autor: "Equipo Creativo de Regalos Únicos",
    }
  ]
}